/**
 * Precomputed actual keystroke diagnostics data for landing page visualization.
 * Auto-generated by scripts/precompute-landing-data.ts from local_db.json.
 */
import { KeyResult, KeyEvent } from "./types";

export const PRECOMPUTED_KEY_STATS: Record<string, KeyResult> = {
  "q": {
    "key": "q",
    "row": 1,
    "x": 0.5,
    "y": 2,
    "z": 0.7960240484014587,
    "confidence": 45,
    "stdev": 102.91061120809339,
    "zSmoothed": 0.7960240484014587,
    "stdevSmoothed": 99.42558510331905
  },
  "w": {
    "key": "w",
    "row": 1,
    "x": 1.5,
    "y": 2,
    "z": 0.6727437808141894,
    "confidence": 33,
    "stdev": 93.18091292904212,
    "zSmoothed": 0.6727437808141894,
    "stdevSmoothed": 95.60879226343663
  },
  "e": {
    "key": "e",
    "row": 1,
    "x": 2.5,
    "y": 2,
    "z": 0.6609317879632328,
    "confidence": 37,
    "stdev": 105.80799854258349,
    "zSmoothed": 0.6609317879632328,
    "stdevSmoothed": 103.52398400324758
  },
  "r": {
    "key": "r",
    "row": 1,
    "x": 3.5,
    "y": 2,
    "z": 0.5738587118860874,
    "confidence": 66,
    "stdev": 101.86889540036607,
    "zSmoothed": 0.5738587118860874,
    "stdevSmoothed": 99.15133493794497
  },
  "t": {
    "key": "t",
    "row": 1,
    "x": 4.5,
    "y": 2,
    "z": 0.8500000000000001,
    "confidence": 50,
    "stdev": 91.75715034639433,
    "zSmoothed": 0.8500000000000001,
    "stdevSmoothed": 88.4008145039831
  },
  "y": {
    "key": "y",
    "row": 1,
    "x": 5.5,
    "y": 2,
    "z": 0.4406664989651833,
    "confidence": 1,
    "stdev": 65.01650023361788,
    "zSmoothed": 0.4406664989651833,
    "stdevSmoothed": 61.29075230062543
  },
  "u": {
    "key": "u",
    "row": 1,
    "x": 6.5,
    "y": 2,
    "z": 0.5787475276891587,
    "confidence": 30,
    "stdev": 26.7222121504158,
    "zSmoothed": 0.5787475276891587,
    "stdevSmoothed": 28.934667447352954
  },
  "i": {
    "key": "i",
    "row": 1,
    "x": 7.5,
    "y": 2,
    "z": 0.2566658569752837,
    "confidence": 2,
    "stdev": 0.9000000059604645,
    "zSmoothed": 0.2566658569752837,
    "stdevSmoothed": 11.895093861509405
  },
  "o": {
    "key": "o",
    "row": 1,
    "x": 8.5,
    "y": 2,
    "z": 0.4489086569817302,
    "confidence": 19,
    "stdev": 25.743948003697344,
    "zSmoothed": 0.4489086569817302,
    "stdevSmoothed": 27.96397696610802
  },
  "p": {
    "key": "p",
    "row": 1,
    "x": 9.5,
    "y": 2,
    "z": 0.4839385943556277,
    "confidence": 12,
    "stdev": 42.38528554012112,
    "zSmoothed": 0.4839385943556277,
    "stdevSmoothed": 42.65741224246262
  },
  "a": {
    "key": "a",
    "row": 2,
    "x": 0.75,
    "y": 1,
    "z": 0.6171037059338527,
    "confidence": 39,
    "stdev": 85.60037602223782,
    "zSmoothed": 0.6171037059338527,
    "stdevSmoothed": 88.65716913291189
  },
  "s": {
    "key": "s",
    "row": 2,
    "x": 1.75,
    "y": 1,
    "z": 0.5145607148039786,
    "confidence": 126,
    "stdev": 113.03634561091125,
    "zSmoothed": 0.5145607148039786,
    "stdevSmoothed": 110.56776409994617
  },
  "d": {
    "key": "d",
    "row": 2,
    "x": 2.75,
    "y": 1,
    "z": 0.553350547851056,
    "confidence": 169,
    "stdev": 84.17803675390243,
    "zSmoothed": 0.553350547851056,
    "stdevSmoothed": 84.17803675390243
  },
  "f": {
    "key": "f",
    "row": 2,
    "x": 3.75,
    "y": 1,
    "z": 0.36387143375087705,
    "confidence": 90,
    "stdev": 79.69239584454087,
    "zSmoothed": 0.36387143375087705,
    "stdevSmoothed": 79.97557198909912
  },
  "g": {
    "key": "g",
    "row": 2,
    "x": 4.75,
    "y": 1,
    "z": 0.5821924633039552,
    "confidence": 47,
    "stdev": 72.23104131134362,
    "zSmoothed": 0.5821924633039552,
    "stdevSmoothed": 67.84779271298015
  },
  "h": {
    "key": "h",
    "row": 2,
    "x": 5.75,
    "y": 1,
    "z": 0.2199554051643081,
    "confidence": 60,
    "stdev": 28.500376995763038,
    "zSmoothed": 0.2199554051643081,
    "stdevSmoothed": 31.596463532624977
  },
  "j": {
    "key": "j",
    "row": 2,
    "x": 6.75,
    "y": 1,
    "z": 0.282344413394566,
    "confidence": 38,
    "stdev": 39.80861799379835,
    "zSmoothed": 0.282344413394566,
    "stdevSmoothed": 36.19900752565835
  },
  "k": {
    "key": "k",
    "row": 2,
    "x": 7.75,
    "y": 1,
    "z": 0.18,
    "confidence": 139,
    "stdev": 34.70370366744604,
    "zSmoothed": 0.18,
    "stdevSmoothed": 34.75964927748913
  },
  "l": {
    "key": "l",
    "row": 2,
    "x": 8.75,
    "y": 1,
    "z": 0.28462014386943824,
    "confidence": 124,
    "stdev": 48.82991410858084,
    "zSmoothed": 0.28462014386943824,
    "stdevSmoothed": 47.89215860874652
  },
  "z": {
    "key": "z",
    "row": 3,
    "x": 1.25,
    "y": 0,
    "z": 0.62235572516598,
    "confidence": 0,
    "stdev": 65.01650023361788,
    "zSmoothed": 0.62235572516598,
    "stdevSmoothed": 92.69345107122432
  },
  "x": {
    "key": "x",
    "row": 3,
    "x": 2.25,
    "y": 0,
    "z": 0.8122536377748557,
    "confidence": 10,
    "stdev": 82.07024064835407,
    "zSmoothed": 0.8122536377748557,
    "stdevSmoothed": 85.02435876614922
  },
  "c": {
    "key": "c",
    "row": 3,
    "x": 3.25,
    "y": 0,
    "z": 0.7802529410061905,
    "confidence": 7,
    "stdev": 90.61957710726125,
    "zSmoothed": 0.7802529410061905,
    "stdevSmoothed": 85.06416149670473
  },
  "v": {
    "key": "v",
    "row": 3,
    "x": 4.25,
    "y": 0,
    "z": 0.8127357009359184,
    "confidence": 7,
    "stdev": 50.136035353893575,
    "zSmoothed": 0.8127357009359184,
    "stdevSmoothed": 55.222843111331244
  },
  "b": {
    "key": "b",
    "row": 3,
    "x": 5.25,
    "y": 0,
    "z": 0.28573896574623975,
    "confidence": 2,
    "stdev": 16.649999991059303,
    "zSmoothed": 0.28573896574623975,
    "stdevSmoothed": 26.704184839167503
  },
  "n": {
    "key": "n",
    "row": 3,
    "x": 6.25,
    "y": 0,
    "z": 0.4863930051372717,
    "confidence": 64,
    "stdev": 27.24485329823188,
    "zSmoothed": 0.4863930051372717,
    "stdevSmoothed": 28.330353885782674
  },
  "m": {
    "key": "m",
    "row": 3,
    "x": 7.25,
    "y": 0,
    "z": 0.4308623655429798,
    "confidence": 94,
    "stdev": 39.86109489942615,
    "zSmoothed": 0.4308623655429798,
    "stdevSmoothed": 39.71958838515813
  },
  "_dummy_comma": {
    "key": "_dummy_comma",
    "row": 3,
    "x": 8.25,
    "y": 0,
    "z": 0.3147334532717685,
    "confidence": 0,
    "stdev": 65.01650023361788,
    "zSmoothed": 0.3147334532717685,
    "stdevSmoothed": 42.51538922083491
  }
};

export const PRECOMPUTED_CYLINDRICAL_EVENTS: KeyEvent[] = [
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 10.199999988079071
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 438.30000001192093
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 74.7999999821186
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 108.59999999403954
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 106.30000001192093
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 46.30000001192093
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 79
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 59.69999998807907
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 66.80000001192093
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 72.69999998807907
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 51.69999998807907
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 56.70000001788139
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 88.19999998807907
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 94.60000002384186
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 154.2999999821186
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 180
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 150.40000000596046
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 119.40000000596046
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 81.30000001192093
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 62.400000005960464
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 135.5
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 81.89999997615814
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 143.10000002384186
  },
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 90.39999997615814
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 60.8999999910593
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 43.099999994039536
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 109.20000000298023
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 123.90000000596046
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 93.09999999403954
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 72.09999999403954
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 122
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 59.79999999701977
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 175.29999999701977
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 47.70000000298023
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 56
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 151.3999999910593
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 74.59999999403954
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 114.1000000089407
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 89.5
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 34.1000000089407
  },
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 32.29999999701977
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 70.69999998807907
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 151.80000001192093
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 75.59999999403954
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 91.40000000596046
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 74.69999998807907
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 86.90000000596046
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 213
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 73.29999999701977
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 84.79999999701977
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 79
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 42.19999998807907
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 120.90000000596046
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 58
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 43.79999999701977
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 83.20000000298023
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 46.70000000298023
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 90.3999999910593
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 76.80000001192093
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 118
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 82.5
  },
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 61.400000005960464
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 94.70000000298023
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 51.099999994039536
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 110.29999999701977
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 98.6000000089407
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 147.3999999910593
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 117.1000000089407
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 94.29999999701977
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 97.3999999910593
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 50
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 49.099999994039536
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 167.1000000089407
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 99.29999999701977
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 73.59999999403954
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 43.79999999701977
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 137.20000000298023
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 130.79999999701977
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 81.70000000298023
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 88.70000000298023
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 76.5
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 122.20000000298023
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 42.099999994039536
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 116.79999999701977
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 64.5
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 117
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 42.400000005960464
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 191.3999999910593
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 145.80000001192093
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 122.09999999403954
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 59.79999999701977
  },
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 86.70000000298023
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 61.8999999910593
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 73.70000000298023
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 65.3999999910593
  },
  {
    "fromKey": "d",
    "toKey": "l",
    "latencyMs": 54.1000000089407
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 104.29999999701977
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 97.8999999910593
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 19.30000001192093
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 57.900000005960464
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 59.900000005960464
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 76.59999999403954
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 61.3999999910593
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 129.90000000596046
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 115.79999999701977
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 88.40000000596046
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 142.3999999910593
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 156
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 121.79999999701977
  },
  {
    "fromKey": "s",
    "toKey": "space",
    "latencyMs": 197.6000000089407
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 57.3999999910593
  },
  {
    "fromKey": "g",
    "toKey": "k",
    "latencyMs": 63.599999994039536
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 102.90000000596046
  },
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 111.8999999910593
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 56.6000000089407
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 126.5
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 93.59999999403954
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 73.09999999403954
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 84.40000000596046
  },
  {
    "fromKey": "d",
    "toKey": "m",
    "latencyMs": 64.90000000596046
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 125.8999999910593
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 513.7000000029802
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 107.70000000298023
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 72.40000000596046
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 541.6999999880791
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 166.40000000596046
  },
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 58
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 68.20000000298023
  },
  {
    "fromKey": "w",
    "toKey": "l",
    "latencyMs": 59.6000000089407
  },
  {
    "fromKey": "m",
    "toKey": "s",
    "latencyMs": 92.70000000298023
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 52.5
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 174.29999999701977
  },
  {
    "fromKey": "l",
    "toKey": "space",
    "latencyMs": 76.70000000298023
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 167
  },
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 121
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 44.5
  },
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 118
  },
  {
    "fromKey": "k",
    "toKey": "s",
    "latencyMs": 86
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 118.40000000596046
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 138.6000000089407
  },
  {
    "fromKey": "e",
    "toKey": "k",
    "latencyMs": 59.099999994039536
  },
  {
    "fromKey": "m",
    "toKey": "f",
    "latencyMs": 131.59999999403954
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 103.40000000596046
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 172.59999999403954
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 128.20000000298023
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 199.09999999403954
  },
  {
    "fromKey": "space",
    "toKey": "d",
    "latencyMs": 173.20000000298023
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 155
  },
  {
    "fromKey": "n",
    "toKey": "f",
    "latencyMs": 166.09999999403954
  },
  {
    "fromKey": "f",
    "toKey": "space",
    "latencyMs": 79.70000000298023
  }
];
