/**
 * Precomputed actual keystroke diagnostics data for landing page visualization.
 * Auto-generated by scripts/precompute-landing-data.ts from local_db.json.
 */
import { KeyResult, KeyEvent } from "./types";

export const PRECOMPUTED_KEY_STATS: Record<string, KeyResult> = {
  "q": {
    "key": "q",
    "row": 1,
    "x": 0.5,
    "y": 2,
    "z": 0.7450963026948436,
    "confidence": 129,
    "stdev": 100.15032707590122,
    "zSmoothed": 0.7450963026948436,
    "stdevSmoothed": 97.6457042741807
  },
  "w": {
    "key": "w",
    "row": 1,
    "x": 1.5,
    "y": 2,
    "z": 0.7678242676486773,
    "confidence": 112,
    "stdev": 79.93844969022916,
    "zSmoothed": 0.7678242676486773,
    "stdevSmoothed": 85.08308159737622
  },
  "e": {
    "key": "e",
    "row": 1,
    "x": 2.5,
    "y": 2,
    "z": 0.6012545940615098,
    "confidence": 125,
    "stdev": 95.92534695029359,
    "zSmoothed": 0.6012545940615098,
    "stdevSmoothed": 93.99962184421888
  },
  "r": {
    "key": "r",
    "row": 1,
    "x": 3.5,
    "y": 2,
    "z": 0.7246628446341903,
    "confidence": 207,
    "stdev": 89.24830214865486,
    "zSmoothed": 0.7246628446341903,
    "stdevSmoothed": 89.61933357082829
  },
  "t": {
    "key": "t",
    "row": 1,
    "x": 4.5,
    "y": 2,
    "z": 0.8011586745070505,
    "confidence": 137,
    "stdev": 107.86764642158971,
    "zSmoothed": 0.8011586745070505,
    "stdevSmoothed": 98.31841230595663
  },
  "y": {
    "key": "y",
    "row": 1,
    "x": 5.5,
    "y": 2,
    "z": 0.2792471125369688,
    "confidence": 8,
    "stdev": 28.16047762304959,
    "zSmoothed": 0.2792471125369688,
    "stdevSmoothed": 41.540141090470854
  },
  "u": {
    "key": "u",
    "row": 1,
    "x": 6.5,
    "y": 2,
    "z": 0.5445308108845971,
    "confidence": 96,
    "stdev": 28.071512854579197,
    "zSmoothed": 0.5445308108845971,
    "stdevSmoothed": 32.80893427880959
  },
  "i": {
    "key": "i",
    "row": 1,
    "x": 7.5,
    "y": 2,
    "z": 0.3161968948820987,
    "confidence": 16,
    "stdev": 51.363429353668764,
    "zSmoothed": 0.3161968948820987,
    "stdevSmoothed": 49.268454740318624
  },
  "o": {
    "key": "o",
    "row": 1,
    "x": 8.5,
    "y": 2,
    "z": 0.44064579168939433,
    "confidence": 72,
    "stdev": 49.267679643339015,
    "zSmoothed": 0.44064579168939433,
    "stdevSmoothed": 49.1361721197585
  },
  "p": {
    "key": "p",
    "row": 1,
    "x": 9.5,
    "y": 2,
    "z": 0.5062041185406837,
    "confidence": 50,
    "stdev": 45.109692262218964,
    "zSmoothed": 0.5062041185406837,
    "stdevSmoothed": 48.03061482924744
  },
  "a": {
    "key": "a",
    "row": 2,
    "x": 0.75,
    "y": 1,
    "z": 0.5749920141454495,
    "confidence": 117,
    "stdev": 102.01739087900218,
    "zSmoothed": 0.5749920141454495,
    "stdevSmoothed": 98.86899849036638
  },
  "s": {
    "key": "s",
    "row": 2,
    "x": 1.75,
    "y": 1,
    "z": 0.4214883208104617,
    "confidence": 388,
    "stdev": 95.98478195527481,
    "zSmoothed": 0.4214883208104617,
    "stdevSmoothed": 96.21434561475887
  },
  "d": {
    "key": "d",
    "row": 2,
    "x": 2.75,
    "y": 1,
    "z": 0.5178338724315505,
    "confidence": 507,
    "stdev": 89.18478119698759,
    "zSmoothed": 0.5178338724315505,
    "stdevSmoothed": 89.18478119698759
  },
  "f": {
    "key": "f",
    "row": 2,
    "x": 3.75,
    "y": 1,
    "z": 0.35413334018113835,
    "confidence": 250,
    "stdev": 72.36957355742234,
    "zSmoothed": 0.35413334018113835,
    "stdevSmoothed": 78.14591256921513
  },
  "g": {
    "key": "g",
    "row": 2,
    "x": 4.75,
    "y": 1,
    "z": 0.5621379905422682,
    "confidence": 130,
    "stdev": 96.83907591168733,
    "zSmoothed": 0.5621379905422682,
    "stdevSmoothed": 89.26038352640099
  },
  "h": {
    "key": "h",
    "row": 2,
    "x": 5.75,
    "y": 1,
    "z": 0.20251893887974481,
    "confidence": 194,
    "stdev": 33.46595979070086,
    "zSmoothed": 0.20251893887974481,
    "stdevSmoothed": 37.265803866462456
  },
  "j": {
    "key": "j",
    "row": 2,
    "x": 6.75,
    "y": 1,
    "z": 0.3155093754040791,
    "confidence": 128,
    "stdev": 59.81133095041824,
    "zSmoothed": 0.3155093754040791,
    "stdevSmoothed": 55.04386589756676
  },
  "k": {
    "key": "k",
    "row": 2,
    "x": 7.75,
    "y": 1,
    "z": 0.18,
    "confidence": 399,
    "stdev": 44.229356582160186,
    "zSmoothed": 0.18,
    "stdevSmoothed": 45.08798628332495
  },
  "l": {
    "key": "l",
    "row": 2,
    "x": 8.75,
    "y": 1,
    "z": 0.2808269925608929,
    "confidence": 336,
    "stdev": 54.04067518533121,
    "zSmoothed": 0.2808269925608929,
    "stdevSmoothed": 53.48745477048103
  },
  "z": {
    "key": "z",
    "row": 3,
    "x": 1.25,
    "y": 0,
    "z": 0.5801330703361508,
    "confidence": 0,
    "stdev": 66.09045225392029,
    "zSmoothed": 0.5801330703361508,
    "stdevSmoothed": 108.61446670004693
  },
  "x": {
    "key": "x",
    "row": 3,
    "x": 2.25,
    "y": 0,
    "z": 0.7960965829391633,
    "confidence": 22,
    "stdev": 143.81078123750603,
    "zSmoothed": 0.7960965829391633,
    "stdevSmoothed": 127.08577968616517
  },
  "c": {
    "key": "c",
    "row": 3,
    "x": 3.25,
    "y": 0,
    "z": 0.7737114932361813,
    "confidence": 29,
    "stdev": 109.51029216658411,
    "zSmoothed": 0.7737114932361813,
    "stdevSmoothed": 108.62871438254459
  },
  "v": {
    "key": "v",
    "row": 3,
    "x": 4.25,
    "y": 0,
    "z": 0.8500000000000001,
    "confidence": 27,
    "stdev": 131.68122376143629,
    "zSmoothed": 0.8500000000000001,
    "stdevSmoothed": 114.12689436496734
  },
  "b": {
    "key": "b",
    "row": 3,
    "x": 5.25,
    "y": 0,
    "z": 0.2896669297637212,
    "confidence": 8,
    "stdev": 39.856829717328,
    "zSmoothed": 0.2896669297637212,
    "stdevSmoothed": 52.0005518710972
  },
  "n": {
    "key": "n",
    "row": 3,
    "x": 6.25,
    "y": 0,
    "z": 0.48769350003647244,
    "confidence": 154,
    "stdev": 40.493698928880825,
    "zSmoothed": 0.48769350003647244,
    "stdevSmoothed": 42.430848588521116
  },
  "m": {
    "key": "m",
    "row": 3,
    "x": 7.25,
    "y": 0,
    "z": 0.4302580223468053,
    "confidence": 271,
    "stdev": 55.4979769511806,
    "zSmoothed": 0.4302580223468053,
    "stdevSmoothed": 54.66062626497939
  },
  "_dummy_comma": {
    "key": "_dummy_comma",
    "row": 3,
    "x": 8.25,
    "y": 0,
    "z": 0.3216790331801037,
    "confidence": 0,
    "stdev": 66.09045225392029,
    "zSmoothed": 0.3216790331801037,
    "stdevSmoothed": 50.792543628347566
  }
};

export const PRECOMPUTED_CYLINDRICAL_EVENTS: KeyEvent[] = [
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 438.30000001192093
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 101.19999998807907
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 101.80000001192093
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 180
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 150.40000000596046
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 105.80000001192093
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 135.5
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 109.20000000298023
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 105.80000001192093
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 101.20000000298023
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 151.80000001192093
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 86.90000000596046
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 75.20000000298023
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 106.29999999701977
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 110.29999999701977
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 86.59999999403954
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 123.69999998807907
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 50
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 167.1000000089407
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 639.3999999910593
  },
  {
    "fromKey": "m",
    "toKey": "d",
    "latencyMs": 113.09999999403954
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 130.79999999701977
  },
  {
    "fromKey": "x",
    "toKey": "d",
    "latencyMs": 153.29999999701977
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 145.80000001192093
  },
  {
    "fromKey": "c",
    "toKey": "d",
    "latencyMs": 545.2000000029802
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 58
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 104.59999999403954
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 76.59999999403954
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 129.90000000596046
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 167
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 57.3999999910593
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 102.90000000596046
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 117.3999999910593
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 135.79999999701977
  },
  {
    "fromKey": "p",
    "toKey": "d",
    "latencyMs": 508.3999999910593
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 152.09999999403954
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 156.5
  },
  {
    "fromKey": "k",
    "toKey": "d",
    "latencyMs": 107.70000000298023
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 76.29999999701977
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 166.40000000596046
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 104.8999999910593
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 139.30000001192093
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 77.70000000298023
  },
  {
    "fromKey": "p",
    "toKey": "d",
    "latencyMs": 58.5
  },
  {
    "fromKey": "g",
    "toKey": "d",
    "latencyMs": 184.29999999701977
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 41.6000000089407
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 172.59999999403954
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 128.40000000596046
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 134.29999999701977
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 106.59999999403954
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 25.599999994039536
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 168.79999999701977
  },
  {
    "fromKey": "w",
    "toKey": "d",
    "latencyMs": 120.80000001192093
  },
  {
    "fromKey": "f",
    "toKey": "d",
    "latencyMs": 155
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 37.8999999910593
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 220.79999999701977
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 153.20000000298023
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 141.09999999403954
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 292.90000000596046
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 125.1000000089407
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 87.19999998807907
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 226.70000000298023
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 182.1000000089407
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 140
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 121
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 92.40000000596046
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 174.09999999403954
  },
  {
    "fromKey": "q",
    "toKey": "d",
    "latencyMs": 128.80000001192093
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 166
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 181.8999999910593
  },
  {
    "fromKey": "q",
    "toKey": "d",
    "latencyMs": 115.6000000089407
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 213.59999999403954
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 131.69999998807907
  },
  {
    "fromKey": "g",
    "toKey": "d",
    "latencyMs": 241.70000000298023
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 149.79999999701977
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 190.29999999701977
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 167.29999999701977
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 125.3999999910593
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 56.3999999910593
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 168.90000000596046
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 136.79999999701977
  },
  {
    "fromKey": "g",
    "toKey": "d",
    "latencyMs": 106.5
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 256
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 134.19999998807907
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 404.09999999403954
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 4
  },
  {
    "fromKey": "p",
    "toKey": "d",
    "latencyMs": 163.59999999403954
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 4.300000011920929
  },
  {
    "fromKey": "l",
    "toKey": "d",
    "latencyMs": 115.20000000298023
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 131.29999999701977
  },
  {
    "fromKey": "h",
    "toKey": "d",
    "latencyMs": 112.40000000596046
  },
  {
    "fromKey": "q",
    "toKey": "d",
    "latencyMs": 161.5
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 105.30000001192093
  },
  {
    "fromKey": "r",
    "toKey": "d",
    "latencyMs": 133.29999999701977
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 116.79999999701977
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 121
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 267.20000000298023
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 137.80000001192093
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 74.1000000089407
  },
  {
    "fromKey": "w",
    "toKey": "d",
    "latencyMs": 167.70000000298023
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 90
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 70.29999999701977
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 476.80000001192093
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 139.5
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 177
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 154.59999999403954
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 126.59999999403954
  },
  {
    "fromKey": "q",
    "toKey": "d",
    "latencyMs": 137.09999999403954
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 94.70000000298023
  },
  {
    "fromKey": "s",
    "toKey": "d",
    "latencyMs": 125.5
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 143.40000000596046
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 135.20000000298023
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 126.79999999701977
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 77.1000000089407
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 78.1000000089407
  },
  {
    "fromKey": "x",
    "toKey": "d",
    "latencyMs": 210.8999999910593
  },
  {
    "fromKey": "c",
    "toKey": "d",
    "latencyMs": 235.90000000596046
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 171.09999999403954
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 119.29999999701977
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 195.8999999910593
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 94.5
  },
  {
    "fromKey": "w",
    "toKey": "d",
    "latencyMs": 135.5
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 70.59999999403954
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 70.5
  },
  {
    "fromKey": "a",
    "toKey": "d",
    "latencyMs": 123.6000000089407
  },
  {
    "fromKey": "n",
    "toKey": "d",
    "latencyMs": 97.90000000596046
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 72.90000000596046
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 40.5
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 159.30000001192093
  },
  {
    "fromKey": "t",
    "toKey": "d",
    "latencyMs": 117.1000000089407
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 39.79999999701977
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 118.20000000298023
  },
  {
    "fromKey": "p",
    "toKey": "d",
    "latencyMs": 441.20000000298023
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 158.40000000596046
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 103.5
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 146.6000000089407
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 123.29999999701977
  },
  {
    "fromKey": "w",
    "toKey": "d",
    "latencyMs": 197.09999999403954
  },
  {
    "fromKey": "v",
    "toKey": "d",
    "latencyMs": 136.6000000089407
  },
  {
    "fromKey": "a",
    "toKey": "d",
    "latencyMs": 72.09999999403954
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 104.09999999403954
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 108
  },
  {
    "fromKey": "w",
    "toKey": "d",
    "latencyMs": 480.70000000298023
  },
  {
    "fromKey": "a",
    "toKey": "d",
    "latencyMs": 156.79999999701977
  },
  {
    "fromKey": "a",
    "toKey": "d",
    "latencyMs": 130.20000000298023
  },
  {
    "fromKey": "e",
    "toKey": "d",
    "latencyMs": 212.70000000298023
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 133.59999999403954
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 118.5
  },
  {
    "fromKey": "a",
    "toKey": "d",
    "latencyMs": 555.0999999940395
  },
  {
    "fromKey": "m",
    "toKey": "d",
    "latencyMs": 89.40000000596046
  },
  {
    "fromKey": "m",
    "toKey": "d",
    "latencyMs": 137.40000000596046
  },
  {
    "fromKey": "o",
    "toKey": "d",
    "latencyMs": 105
  },
  {
    "fromKey": "q",
    "toKey": "d",
    "latencyMs": 137.29999999701977
  },
  {
    "fromKey": "m",
    "toKey": "d",
    "latencyMs": 494.90000000596046
  },
  {
    "fromKey": "x",
    "toKey": "d",
    "latencyMs": 152.70000000298023
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 44.599999994039536
  },
  {
    "fromKey": "p",
    "toKey": "d",
    "latencyMs": 106.5
  },
  {
    "fromKey": "j",
    "toKey": "d",
    "latencyMs": 144.59999999403954
  },
  {
    "fromKey": "a",
    "toKey": "d",
    "latencyMs": 203.70000000298023
  },
  {
    "fromKey": "a",
    "toKey": "d",
    "latencyMs": 181
  },
  {
    "fromKey": "m",
    "toKey": "d",
    "latencyMs": 74
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 325.5
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 92.1000000089407
  },
  {
    "fromKey": "m",
    "toKey": "d",
    "latencyMs": 68.79999999701977
  },
  {
    "fromKey": "u",
    "toKey": "d",
    "latencyMs": 45.8999999910593
  },
  {
    "fromKey": "p",
    "toKey": "d",
    "latencyMs": 121.5
  },
  {
    "fromKey": "q",
    "toKey": "d",
    "latencyMs": 257.90000000596046
  },
  {
    "fromKey": "g",
    "toKey": "d",
    "latencyMs": 76.20000000298023
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 91.79999999701977
  },
  {
    "fromKey": "p",
    "toKey": "d",
    "latencyMs": 211.8999999910593
  },
  {
    "fromKey": "i",
    "toKey": "d",
    "latencyMs": 180.20000000298023
  },
  {
    "fromKey": "p",
    "toKey": "d",
    "latencyMs": 273.20000000298023
  },
  {
    "fromKey": "m",
    "toKey": "d",
    "latencyMs": 92
  },
  {
    "fromKey": "g",
    "toKey": "d",
    "latencyMs": 232.1000000089407
  },
  {
    "fromKey": "a",
    "toKey": "d",
    "latencyMs": 470.40000000596046
  },
  {
    "fromKey": "g",
    "toKey": "d",
    "latencyMs": 55.70000000298023
  },
  {
    "fromKey": "p",
    "toKey": "d",
    "latencyMs": 150.70000000298023
  },
  {
    "fromKey": "a",
    "toKey": "d",
    "latencyMs": 145.90000000596046
  },
  {
    "fromKey": "b",
    "toKey": "d",
    "latencyMs": 176.22329464672285
  },
  {
    "fromKey": "b",
    "toKey": "d",
    "latencyMs": 208.6124167606051
  },
  {
    "fromKey": "y",
    "toKey": "d",
    "latencyMs": 204.8866649237591
  },
  {
    "fromKey": "y",
    "toKey": "d",
    "latencyMs": 216.17459613211264
  },
  {
    "fromKey": "z",
    "toKey": "d",
    "latencyMs": 218.92037291564145
  },
  {
    "fromKey": "z",
    "toKey": "d",
    "latencyMs": 214.51622350561368
  }
];
